### ISSUE TITLE
problem with cassandra 3

### ISSUE THREAD

**Issue by masoodg** [comeara/pillar#30]
Hi,

It seems that pillar is not compatible with Cassandra 3.
I'm using 
`  "com.datastax.cassandra" % "cassandra-driver-core" % "3.0.0",
`

And when using latest version of pillar, I get the following error:

```
Exception encountered when attempting to run a suite with class name: common.utils.cassandra.ConnectionAndQuerySpec *** ABORTED ***
[info]   java.lang.NoSuchMethodError: com.datastax.driver.core.Row.getDate(Ljava/lang/String;)Ljava/util/Date;
[info]   at com.chrisomeara.pillar.AppliedMigrations$$anonfun$apply$1.apply(AppliedMigrations.scala:12)
[info]   at com.chrisomeara.pillar.AppliedMigrations$$anonfun$apply$1.apply(AppliedMigrations.scala:12)
[info]   at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
[info]   at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
[info]   at scala.collection.Iterator$class.foreach(Iterator.scala:743)
[info]   at scala.collection.AbstractIterator.foreach(Iterator.scala:1195)
[info]   at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
[info]   at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[info]   at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
[info]   at scala.collection.AbstractTraversable.map(Traversable.scala:104)
```

**Comment by magro** [comment]
https://github.com/Galeria-Kaufhof/pillar has been upgraded to 3.0.0 of the driver, it's a better maintained fork.

**Comment by comeara** [comment]
Version 2.2 has been tested against Cassandra 3.

**Comment by bachateraconfuego** [comment]
Hi, What about Cassandra 2.1.14? I am seeing this issue too.

**Comment by comeara** [comment]
Yes, recent releases have been tested against Cassandra 2.1. Can you please give me some information about the problem you are experiencing?

**Comment by gudyo** [comment]
So i get what i believe is the same error as above except for java:

```	at com.google.inject.internal.Errors.throwProvisionExceptionIfErrorsExist(Errors.java:482)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:67)
	at com.google.inject.internal.InjectorImpl.injectMembers(InjectorImpl.java:984)
	at com.fitbit.dsts.common.test.AbstractComponentTestBase.setUp(AbstractComponentTestBase.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.NoSuchMethodError: com.datastax.driver.core.Row.getDate(Ljava/lang/String;)Ljava/util/Date;
	at com.contrastsecurity.cassandra.migration.dao.SchemaVersionDAO.findAppliedMigrations(SchemaVersionDAO.java:168)
	at com.contrastsecurity.cassandra.migration.info.MigrationInfoService.refresh(MigrationInfoService.java:66)
	at com.contrastsecurity.cassandra.migration.action.Migrate.run(Migrate.java:43)
	at com.contrastsecurity.cassandra.migration.CassandraMigration$1.execute(CassandraMigration.java:76)
	at com.contrastsecurity.cassandra.migration.CassandraMigration$1.execute(CassandraMigration.java:67)
	at com.contrastsecurity.cassandra.migration.CassandraMigration.execute(CassandraMigration.java:157)
at com.contrastsecurity.cassandra.migration.CassandraMigration.migrate(CassandraMigration.java:67)
	```

I am using EmbeddedCassandra here with the following packages:
'com.datastax.cassandra:cassandra-driver-mapping:3.1.3'
'com.datastax.cassandra:cassandra-driver-extras:3.1.3'
'com.datastax.cassandra:cassandra-driver-core:3.1.3'

**Comment by gudyo** [comment]
Oh u know... I think my comment (and error) aren't related to pillar :(. I'am not using pillar. I'm sorry - this thread showed up in my google search for the error

**Comment by comeara** [comment]
Yes. I was just typing that...

Those packages look like they may belong to this repo:

https://github.com/Contrast-Security-OSS/cassandra-migration

Or maybe a fork of that repo.

**Comment by gudyo** [comment]
hmm maybe Thank you! Sorry again!
